##Numpy array operations

Lets first see how arrays behave like “vectors/matrices” when operations happen element-wise.

In [2]:
import numpy as np

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a+b)
print(a // b)
print(a-b)
print(a*b)

[11 22 33 44]
[10 10 10 10]
[ 9 18 27 36]
[ 10  40  90 160]


These things are already different from List and if we talk about one more special power it is **Broadcasting**

In [3]:
a = np.array([1,2,3,4])

print(a * 2)

[2 4 6 8]


Even these things work with different shaped array the calculations will happen on every row. but dimensions must match

In [4]:
a = np.array([[1,2,3], [4,5,6]])

print(a * 5)

[[ 5 10 15]
 [20 25 30]]


#Aggregate Functions

These functions are used to calculate the statistics on arrays.

In [5]:
a = np.array([2,10,12,15,16,20])

print(np.sum(a))
print(np.mean(a))
print(np.min(a))
print(np.max(a))
print(np.std(a))
print(np.var(a))

75
12.5
2
20
5.649483752226097
31.916666666666668


You can also do the axis based operations row-Wise and Colum-wise

In [6]:
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [7]:
print(np.sum(data,axis=1))

[ 6 15 24]
