##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

arr[[0,2]]

array([10, 30])

You can do this fancy indexing in 2D Matrix aswell

In [8]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,2], [2,3]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([ 3, 12])

##Conditional Selection
Find values based on conditions or replace them.

In [12]:
arr = np.array([5,12,15,7,20,23])
arr[arr>10]
np.where(arr>10)
np.where(arr>10, arr,0)

array([ 0, 12, 15,  0, 20, 23])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [13]:
np.sort(arr)

array([ 5,  7, 12, 15, 20, 23])

In [15]:
np.argsort(arr)

array([0, 3, 1, 2, 4, 5])

##Concatenation & Stacking

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [19]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [20]:
a

array([[1, 2],
       [3, 4]])

In [21]:
b

array([[5, 6],
       [7, 8]])

In [22]:
np.vstack([b,a])

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [23]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])