##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
arr

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-3])

1
4


Now lets see the 2D indexing aswell

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1]

array([4, 5, 6])

In [ ]:
arr[1,1]

np.int64(5)

Now we can also do the slicing lets see the **slicing in 1D**

In [ ]:
a = ([1,2,3,4,5,6])
a[:3]

[1, 2, 3]

1D slicing was really easy now lets see the **slicing in 2D**

In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)
arr[0:2, 0:2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

There is one more thing known as **Boolean indexing**

In [ ]:
arr = np.array([5,10,20,30,40,50])
print(arr>12)
print(arr[arr>12])

[False False  True  True  True  True]
[20 30 40 50]


In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr[arr>=5]

array([5, 6, 7, 8, 9])

## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [ ]:
a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [ ]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])